schema_version = "1.0.0"

id = "gta_mlo_scaleform_tools"
version = "1.0.1"
name = "MLOScaleformTools"
tagline = "Scaleform Tools for minimaps"
maintainer = "rubyys"
type = "add-on"

website = "https://github.com/Rubyyss/MLOScaleformTool"

tags = [
    "Scaleform", 
    "Import-Export", 
    "3D View", 
    "Curves", 
    "Calculator", 
    "2D Size", 
    "Minimap", 
    "GTA V", 
    "MLO"
]

blender_version_min = "4.4.0"

license = ["SPDX:MIT"]
copyright = ["2025-2026 rubyys"]

[permissions]
files = "Import/export SVG files. Save/load presets."
clipboard = "Copy/paste object location and rotation."
