schema_version = "1.0.0"

id = "gta_mlo_scaleform_tools"
version = "2.2.1"
name = "MLOScaleformTools"
tagline = "Grand Theft Auto V Scaleform Tools"
maintainer = "rubyys <tecladogb@gmail.com>"
type = "add-on"

website = "https://github.com/Rubyyss/MLOScaleformTool"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:MIT",]
copyright = ["2025-2026 rubyys"]

[permissions]
files = "Import/export SVG Files. Save/load presets."
clipboard = "Copy/paste location and rotation of objects."