{
    "bl_info": {
        "name": "MLOScaleformTool",
        "author": "rubyys",
        "version": (1, 0, 0),
        "blender": (4, 4, 0),
        "location": "View3D > Sidebar > Import-Export" > Curve > SVG >,
        "description": "Minimap Tool For V",
        "warning": "",
        "wiki_url": "",
        "category": "3D View",
        "support": "COMMUNITY"
    },
    "manifest": {
        "name": "gta_MloScaleformTool",
        "version": "1.0.0",
        "type": "extension",
        "python_requires": ">=3.7",
        "dependencies": [
            {
                "name": "numpy",
                "version": ">=1.21.0"
            }
        ],
        "keywords": [
            "blender",
            "addon",
            "3d",
            "tool"
        ],
        "licenses": [
            {
                "type": "MIT",
                "href": "https://opensource.org/licenses/MIT"
            }
        ],
        "development": {
            "status": "alpha",
            "repository": {
                "type": "git",
                "url": "https://github.com/Rubyyss/MLOScaleformTool"
            }
        },
        "compatibility": {
            "blender_versions": [
                "3.3.0",
                "3.4.0",
                "3.5.0",
                "4.0.0"
                "4.4.0"
            ],
            "platforms": [
                "windows-x64",
            ]
        },
        "installation": {
            "method": [
                "Blender Preferences",
                "Manual Installation"
            ],
            "requirements": [
                "Blender 3.3+",
                "Python 3.7+"
            ]
        }
    }
}